/* eslint-disable */
import * as types from "./graphql";
import type { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "query About($locale: I18NLocaleCode) {\n  about(locale: $locale) {\n    landing {\n      id\n      title\n      subtitle\n      text\n      image {\n        caption\n        url\n        alternativeText\n      }\n    }\n    whyUs {\n      general {\n        text\n        title\n        subtitle\n        image {\n          caption\n          alternativeText\n          url\n          width\n        }\n      }\n      points {\n        id\n        subtitle\n        title\n        iconName\n      }\n    }\n    csr {\n      goals {\n        title\n        id\n        subtitle\n        icon\n      }\n      title\n      subtitle\n      text\n    }\n    locale\n    mission {\n      id\n      image {\n        height\n        name\n        url\n        width\n        caption\n        alternativeText\n      }\n      title\n      subtitle\n      text\n    }\n    vision {\n      general {\n        image {\n          caption\n          alternativeText\n          documentId\n          height\n          name\n          size\n          url\n          width\n        }\n        subtitle\n        text\n        title\n      }\n      goals {\n        id\n        title\n        value\n      }\n    }\n    values {\n      general {\n        image {\n          alternativeText\n          caption\n          width\n          url\n        }\n        subtitle\n        text\n        title\n      }\n      values {\n        id\n        title\n        value\n      }\n    }\n  }\n}": typeof types.AboutDocument;
    "query Certificates {\n  certificates {\n    audit_report {\n      alternativeText\n      caption\n      url\n    }\n    certificate {\n      alternativeText\n      caption\n      formats\n      name\n      url\n    }\n    documentId\n    description\n    logo {\n      alternativeText\n      caption\n      formats\n      url\n    }\n    name\n  }\n}": typeof types.CertificatesDocument;
    "query Footer($locale: I18NLocaleCode) {\n  footer(locale: $locale) {\n    brandName\n    brandDescription\n    quickLinks {\n      label\n      href\n    }\n    address\n    email\n    legalLinks {\n      label\n      href\n    }\n    copyrightText\n  }\n}": typeof types.FooterDocument;
    "query GetHomeData($locale: I18NLocaleCode) {\n  brands(locale: $locale) {\n    documentId\n    name\n    slug\n    description\n    logo {\n      url\n      alternativeText\n    }\n  }\n  homepage {\n    qualityMarketing {\n      points {\n        iconName\n        subtitle\n        title\n        id\n      }\n      general {\n        id\n        image {\n          alternativeText\n          caption\n          url\n        }\n        title\n        text\n        subtitle\n      }\n    }\n    hero {\n      ctaPrimary\n      ctaSecondary\n      description\n      id\n      image {\n        alternativeText\n        url\n      }\n      primaryLink\n      secondaryLink\n      subtitle\n      title\n    }\n    map {\n      description\n      exportedCountries\n      countryToIso\n      countryToContinent\n      id\n      subtitle\n      title\n    }\n  }\n}": typeof types.GetHomeDataDocument;
    "query GetAllOfferings {\n  offerings {\n    documentId\n    availability\n    isMedjoolDate\n    pack_options {\n      amount\n      documentId\n      displayLabel\n      unit\n    }\n    brand {\n      name\n      slug\n      documentId\n      logo {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    product {\n      documentId\n      name\n      description\n      category {\n        name\n        documentId\n      }\n      image {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    images {\n      documentId\n      alternativeText\n      url\n      width\n    }\n    dateSpecifications {\n      grade\n      sizes\n      pack_options {\n        documentId\n        displayLabel\n        amount\n        unit\n        amountMin\n        amountMax\n        note\n        applicable_sizes\n      }\n    }\n  }\n}\n\nquery GetOffering($id: ID!) {\n  offering(documentId: $id) {\n    documentId\n    availability\n    isMedjoolDate\n    pack_options {\n      amount\n      displayLabel\n      unit\n      documentId\n    }\n    brand {\n      name\n      slug\n      documentId\n      logo {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    product {\n      documentId\n      name\n      description\n      category {\n        name\n      }\n      image {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    images {\n      documentId\n      alternativeText\n      url\n      width\n    }\n    dateSpecifications {\n      grade\n      sizes\n      pack_options {\n        documentId\n        displayLabel\n        amount\n        unit\n        amountMin\n        amountMax\n        note\n        applicable_sizes\n      }\n    }\n  }\n}": typeof types.GetAllOfferingsDocument;
    "mutation CreateOrder($data: OrderInput!) {\n  createOrder(data: $data) {\n    documentId\n    orderNumber\n    status\n    customer {\n      documentId\n      email\n    }\n  }\n}": typeof types.CreateOrderDocument;
};
const documents: Documents = {
    "query About($locale: I18NLocaleCode) {\n  about(locale: $locale) {\n    landing {\n      id\n      title\n      subtitle\n      text\n      image {\n        caption\n        url\n        alternativeText\n      }\n    }\n    whyUs {\n      general {\n        text\n        title\n        subtitle\n        image {\n          caption\n          alternativeText\n          url\n          width\n        }\n      }\n      points {\n        id\n        subtitle\n        title\n        iconName\n      }\n    }\n    csr {\n      goals {\n        title\n        id\n        subtitle\n        icon\n      }\n      title\n      subtitle\n      text\n    }\n    locale\n    mission {\n      id\n      image {\n        height\n        name\n        url\n        width\n        caption\n        alternativeText\n      }\n      title\n      subtitle\n      text\n    }\n    vision {\n      general {\n        image {\n          caption\n          alternativeText\n          documentId\n          height\n          name\n          size\n          url\n          width\n        }\n        subtitle\n        text\n        title\n      }\n      goals {\n        id\n        title\n        value\n      }\n    }\n    values {\n      general {\n        image {\n          alternativeText\n          caption\n          width\n          url\n        }\n        subtitle\n        text\n        title\n      }\n      values {\n        id\n        title\n        value\n      }\n    }\n  }\n}":
        types.AboutDocument,
    "query Certificates {\n  certificates {\n    audit_report {\n      alternativeText\n      caption\n      url\n    }\n    certificate {\n      alternativeText\n      caption\n      formats\n      name\n      url\n    }\n    documentId\n    description\n    logo {\n      alternativeText\n      caption\n      formats\n      url\n    }\n    name\n  }\n}":
        types.CertificatesDocument,
    "query Footer($locale: I18NLocaleCode) {\n  footer(locale: $locale) {\n    brandName\n    brandDescription\n    quickLinks {\n      label\n      href\n    }\n    address\n    email\n    legalLinks {\n      label\n      href\n    }\n    copyrightText\n  }\n}":
        types.FooterDocument,
    "query GetHomeData($locale: I18NLocaleCode) {\n  brands(locale: $locale) {\n    documentId\n    name\n    slug\n    description\n    logo {\n      url\n      alternativeText\n    }\n  }\n  homepage {\n    qualityMarketing {\n      points {\n        iconName\n        subtitle\n        title\n        id\n      }\n      general {\n        id\n        image {\n          alternativeText\n          caption\n          url\n        }\n        title\n        text\n        subtitle\n      }\n    }\n    hero {\n      ctaPrimary\n      ctaSecondary\n      description\n      id\n      image {\n        alternativeText\n        url\n      }\n      primaryLink\n      secondaryLink\n      subtitle\n      title\n    }\n    map {\n      description\n      exportedCountries\n      countryToIso\n      countryToContinent\n      id\n      subtitle\n      title\n    }\n  }\n}":
        types.GetHomeDataDocument,
    "query GetAllOfferings {\n  offerings {\n    documentId\n    availability\n    isMedjoolDate\n    pack_options {\n      amount\n      documentId\n      displayLabel\n      unit\n    }\n    brand {\n      name\n      slug\n      documentId\n      logo {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    product {\n      documentId\n      name\n      description\n      category {\n        name\n        documentId\n      }\n      image {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    images {\n      documentId\n      alternativeText\n      url\n      width\n    }\n    dateSpecifications {\n      grade\n      sizes\n      pack_options {\n        documentId\n        displayLabel\n        amount\n        unit\n        amountMin\n        amountMax\n        note\n        applicable_sizes\n      }\n    }\n  }\n}\n\nquery GetOffering($id: ID!) {\n  offering(documentId: $id) {\n    documentId\n    availability\n    isMedjoolDate\n    pack_options {\n      amount\n      displayLabel\n      unit\n      documentId\n    }\n    brand {\n      name\n      slug\n      documentId\n      logo {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    product {\n      documentId\n      name\n      description\n      category {\n        name\n      }\n      image {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    images {\n      documentId\n      alternativeText\n      url\n      width\n    }\n    dateSpecifications {\n      grade\n      sizes\n      pack_options {\n        documentId\n        displayLabel\n        amount\n        unit\n        amountMin\n        amountMax\n        note\n        applicable_sizes\n      }\n    }\n  }\n}":
        types.GetAllOfferingsDocument,
    "mutation CreateOrder($data: OrderInput!) {\n  createOrder(data: $data) {\n    documentId\n    orderNumber\n    status\n    customer {\n      documentId\n      email\n    }\n  }\n}":
        types.CreateOrderDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
    source: "query About($locale: I18NLocaleCode) {\n  about(locale: $locale) {\n    landing {\n      id\n      title\n      subtitle\n      text\n      image {\n        caption\n        url\n        alternativeText\n      }\n    }\n    whyUs {\n      general {\n        text\n        title\n        subtitle\n        image {\n          caption\n          alternativeText\n          url\n          width\n        }\n      }\n      points {\n        id\n        subtitle\n        title\n        iconName\n      }\n    }\n    csr {\n      goals {\n        title\n        id\n        subtitle\n        icon\n      }\n      title\n      subtitle\n      text\n    }\n    locale\n    mission {\n      id\n      image {\n        height\n        name\n        url\n        width\n        caption\n        alternativeText\n      }\n      title\n      subtitle\n      text\n    }\n    vision {\n      general {\n        image {\n          caption\n          alternativeText\n          documentId\n          height\n          name\n          size\n          url\n          width\n        }\n        subtitle\n        text\n        title\n      }\n      goals {\n        id\n        title\n        value\n      }\n    }\n    values {\n      general {\n        image {\n          alternativeText\n          caption\n          width\n          url\n        }\n        subtitle\n        text\n        title\n      }\n      values {\n        id\n        title\n        value\n      }\n    }\n  }\n}",
): (typeof documents)["query About($locale: I18NLocaleCode) {\n  about(locale: $locale) {\n    landing {\n      id\n      title\n      subtitle\n      text\n      image {\n        caption\n        url\n        alternativeText\n      }\n    }\n    whyUs {\n      general {\n        text\n        title\n        subtitle\n        image {\n          caption\n          alternativeText\n          url\n          width\n        }\n      }\n      points {\n        id\n        subtitle\n        title\n        iconName\n      }\n    }\n    csr {\n      goals {\n        title\n        id\n        subtitle\n        icon\n      }\n      title\n      subtitle\n      text\n    }\n    locale\n    mission {\n      id\n      image {\n        height\n        name\n        url\n        width\n        caption\n        alternativeText\n      }\n      title\n      subtitle\n      text\n    }\n    vision {\n      general {\n        image {\n          caption\n          alternativeText\n          documentId\n          height\n          name\n          size\n          url\n          width\n        }\n        subtitle\n        text\n        title\n      }\n      goals {\n        id\n        title\n        value\n      }\n    }\n    values {\n      general {\n        image {\n          alternativeText\n          caption\n          width\n          url\n        }\n        subtitle\n        text\n        title\n      }\n      values {\n        id\n        title\n        value\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
    source: "query Certificates {\n  certificates {\n    audit_report {\n      alternativeText\n      caption\n      url\n    }\n    certificate {\n      alternativeText\n      caption\n      formats\n      name\n      url\n    }\n    documentId\n    description\n    logo {\n      alternativeText\n      caption\n      formats\n      url\n    }\n    name\n  }\n}",
): (typeof documents)["query Certificates {\n  certificates {\n    audit_report {\n      alternativeText\n      caption\n      url\n    }\n    certificate {\n      alternativeText\n      caption\n      formats\n      name\n      url\n    }\n    documentId\n    description\n    logo {\n      alternativeText\n      caption\n      formats\n      url\n    }\n    name\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
    source: "query Footer($locale: I18NLocaleCode) {\n  footer(locale: $locale) {\n    brandName\n    brandDescription\n    quickLinks {\n      label\n      href\n    }\n    address\n    email\n    legalLinks {\n      label\n      href\n    }\n    copyrightText\n  }\n}",
): (typeof documents)["query Footer($locale: I18NLocaleCode) {\n  footer(locale: $locale) {\n    brandName\n    brandDescription\n    quickLinks {\n      label\n      href\n    }\n    address\n    email\n    legalLinks {\n      label\n      href\n    }\n    copyrightText\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
    source: "query GetHomeData($locale: I18NLocaleCode) {\n  brands(locale: $locale) {\n    documentId\n    name\n    slug\n    description\n    logo {\n      url\n      alternativeText\n    }\n  }\n  homepage {\n    qualityMarketing {\n      points {\n        iconName\n        subtitle\n        title\n        id\n      }\n      general {\n        id\n        image {\n          alternativeText\n          caption\n          url\n        }\n        title\n        text\n        subtitle\n      }\n    }\n    hero {\n      ctaPrimary\n      ctaSecondary\n      description\n      id\n      image {\n        alternativeText\n        url\n      }\n      primaryLink\n      secondaryLink\n      subtitle\n      title\n    }\n    map {\n      description\n      exportedCountries\n      countryToIso\n      countryToContinent\n      id\n      subtitle\n      title\n    }\n  }\n}",
): (typeof documents)["query GetHomeData($locale: I18NLocaleCode) {\n  brands(locale: $locale) {\n    documentId\n    name\n    slug\n    description\n    logo {\n      url\n      alternativeText\n    }\n  }\n  homepage {\n    qualityMarketing {\n      points {\n        iconName\n        subtitle\n        title\n        id\n      }\n      general {\n        id\n        image {\n          alternativeText\n          caption\n          url\n        }\n        title\n        text\n        subtitle\n      }\n    }\n    hero {\n      ctaPrimary\n      ctaSecondary\n      description\n      id\n      image {\n        alternativeText\n        url\n      }\n      primaryLink\n      secondaryLink\n      subtitle\n      title\n    }\n    map {\n      description\n      exportedCountries\n      countryToIso\n      countryToContinent\n      id\n      subtitle\n      title\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
    source: "query GetAllOfferings {\n  offerings {\n    documentId\n    availability\n    isMedjoolDate\n    pack_options {\n      amount\n      documentId\n      displayLabel\n      unit\n    }\n    brand {\n      name\n      slug\n      documentId\n      logo {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    product {\n      documentId\n      name\n      description\n      category {\n        name\n        documentId\n      }\n      image {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    images {\n      documentId\n      alternativeText\n      url\n      width\n    }\n    dateSpecifications {\n      grade\n      sizes\n      pack_options {\n        documentId\n        displayLabel\n        amount\n        unit\n        amountMin\n        amountMax\n        note\n        applicable_sizes\n      }\n    }\n  }\n}\n\nquery GetOffering($id: ID!) {\n  offering(documentId: $id) {\n    documentId\n    availability\n    isMedjoolDate\n    pack_options {\n      amount\n      displayLabel\n      unit\n      documentId\n    }\n    brand {\n      name\n      slug\n      documentId\n      logo {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    product {\n      documentId\n      name\n      description\n      category {\n        name\n      }\n      image {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    images {\n      documentId\n      alternativeText\n      url\n      width\n    }\n    dateSpecifications {\n      grade\n      sizes\n      pack_options {\n        documentId\n        displayLabel\n        amount\n        unit\n        amountMin\n        amountMax\n        note\n        applicable_sizes\n      }\n    }\n  }\n}",
): (typeof documents)["query GetAllOfferings {\n  offerings {\n    documentId\n    availability\n    isMedjoolDate\n    pack_options {\n      amount\n      documentId\n      displayLabel\n      unit\n    }\n    brand {\n      name\n      slug\n      documentId\n      logo {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    product {\n      documentId\n      name\n      description\n      category {\n        name\n        documentId\n      }\n      image {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    images {\n      documentId\n      alternativeText\n      url\n      width\n    }\n    dateSpecifications {\n      grade\n      sizes\n      pack_options {\n        documentId\n        displayLabel\n        amount\n        unit\n        amountMin\n        amountMax\n        note\n        applicable_sizes\n      }\n    }\n  }\n}\n\nquery GetOffering($id: ID!) {\n  offering(documentId: $id) {\n    documentId\n    availability\n    isMedjoolDate\n    pack_options {\n      amount\n      displayLabel\n      unit\n      documentId\n    }\n    brand {\n      name\n      slug\n      documentId\n      logo {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    product {\n      documentId\n      name\n      description\n      category {\n        name\n      }\n      image {\n        documentId\n        alternativeText\n        url\n        width\n      }\n    }\n    images {\n      documentId\n      alternativeText\n      url\n      width\n    }\n    dateSpecifications {\n      grade\n      sizes\n      pack_options {\n        documentId\n        displayLabel\n        amount\n        unit\n        amountMin\n        amountMax\n        note\n        applicable_sizes\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
    source: "mutation CreateOrder($data: OrderInput!) {\n  createOrder(data: $data) {\n    documentId\n    orderNumber\n    status\n    customer {\n      documentId\n      email\n    }\n  }\n}",
): (typeof documents)["mutation CreateOrder($data: OrderInput!) {\n  createOrder(data: $data) {\n    documentId\n    orderNumber\n    status\n    customer {\n      documentId\n      email\n    }\n  }\n}"];

export function graphql(source: string) {
    return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
    TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
